### PR TITLE
PRESIDECMS-559 error thrown on NULL filters

### PR DESCRIPTION
**Pull request by sebduggan**
Also a minor typo fix to the comments in standard_page.cfc

### CODE REVIEW

**Comment by sebduggan** [comment]
Apologies - there are a couple of other commits which have crept into this PR...

**Comment by DominicWatson** [comment]
no worries, should do all PRs from a fresh branch. That way each distinct change can be separated (subsequent pushes to any branch that you've made a PR from will automatically make their way into the PR)l

**Comment by DominicWatson** [comment]
There's a guide here for how to do PRs for Preside: https://docs.presidecms.com/contribguides/submittingchanges.html

**Comment by DominicWatson** [comment]
I'll merge these all as one though given the minor nature of some of these.

**Comment by DominicWatson** [comment]
Closing this pending resubmission in separate branches

**Pull request closed without merging**
