### PR TITLE
Added a fix to the Email Center Link modal problem with email variables.

### PR DESCRIPTION
**Pull request by cfmitrah**
https://presidecms.atlassian.net/browse/PRESIDECMS-1943

### CODE REVIEW

**Comment by DominicWatson** [comment]
Thanks for this @cfmitrah - I'm not 100% sure on this. @sebduggan did you work on the email variable feature in CKEditor? Are you able to review?

**Comment by sebduggan** [comment]
This looks good to merge. I'm sure it used to work, so not sure what changed! But I've teseted the fix, and it seems good.

**Review by sebduggan — APPROVED** [review]
This looks good to merge. I'm sure it used to work, so not sure what changed! But I've teseted the fix, and it seems good.

**Comment by DominicWatson** [comment]
Thanks Seb - I'll get into our upcoming release branch and we can QA before releasing the next hotfix.

**Pull request merged**
