### PR TITLE
Feature presidecms 2135 allow js confirmation open new window

### PR DESCRIPTION
**Pull request by john5onCheng**

### CODE REVIEW

**Comment by DominicWatson** [comment]
Great stuff, merging into upcoming release for QA.

**Comment by DominicWatson** [comment]
@john5onCheng - just doing some testing on this and can see that links _do_ open in a new window/tab. However, when you return to the original tab, the dialog is still open. In the case where the link target is not the default same window behaviour, we should close the dialog at this point also.

**Comment by john5onCheng** [comment]
Hi @DominicWatson ,

I have added the code to close dialog.

**Comment by DominicWatson** [comment]
Nice one thanks @john5onCheng  - merging ready for retest

**Pull request merged**
