### PR TITLE
PRESIDECMS-1093

### PR DESCRIPTION
**Pull request by john5onCheng**
Apply default group by

### CODE REVIEW

**Comment by DominicWatson** [comment]
Hey @john5onCheng thanks for this.

This logic does not seem correct to me, though. Automatically adding a groupBy just on the id field  whenever there are extra filters does not make sense + will break in non-mysql DBs in many cases.

What is it that is trying to be fixed here? I think an alternative approach is required.

**Comment by john5onCheng** [comment]
hi @DominicWatson,

I have made the changes to always return the groupBy with object id when autoGroupBy is true and autoGeneratedGroupBy value is empty

Many thanks
Johnson

**Comment by DominicWatson** [comment]
But this is just repeating and over-writing the logic in the line before... (i.e. see the function `_autoCalculateGroupBy()`)

It sounds like the logic in that function is what will need updating so that it takes filters as well as select fields into account.

**Comment by john5onCheng** [comment]
hi @DominicWatson ,

The case i am working on is to group by the "website user" when it has query on "contact product" (many-to-many) table through the "contact" object.

Therefore, taking the contact product does not able to provide direct relationship to form a group by for website_user.id. I am not sure is that correct to always return group by value as long as it's not SQL aggregate function when "autogroupby" is set to true when performing selectData()?

Many thanks
J

**Comment by DominicWatson** [comment]
Thanks for this @john5onCheng. This still makes me uneasy though. Doing this will change many existing queries, potentially unpredictably. If we want to force a query to group by everything then we should make this a separate argument:

```
selectData(
    // ...
    , forceAutoGroupBy = true
);
```

Only when this is set to true (default it to false), should we _always_ group by all fields other than aggregates. Does this make sense?

**Comment by DominicWatson** [comment]
Reviewed this more closely. The issue is in fact resolved with a simple `distinct=true` on the relevant selectData() calls (any selectData() call that uses dynamic filters).

**Comment by DominicWatson** [comment]
Thank you for the time looking into it though @john5onCheng

**Pull request closed without merging**
