### PR TITLE
PRESIDECMS-1981 user last visited page rules expression throwing error

### PR DESCRIPTION
**Pull request by annbelievable**
Hi @DominicWatson ,

Like this one?

### CODE REVIEW

**Comment by DominicWatson** [comment]
Perfect, thanks @annbelievable - will look to merge this asap. Is there a corresponding JIRA issue with description of the bug?

**Comment by annbelievable** [comment]
there is no ticket for this issue, just came across it and submitted the fix

**Comment by DominicWatson** [comment]
Oh @annbelievable - I just noticed that there are no commits in this branch other than the branch init! Could you:

1. Create ticket with description
2. Edit PR title to include ticket number
3. Add the commit to your remove code branch :)

I can then get this merged asap.

**Comment by annbelievable** [comment]
Hi @DominicWatson,

1) The ticket created: https://presidecms.atlassian.net/browse/PRESIDECMS-1981
2) The title of the PR has also been updated
3) The changes have been commited.

Thank you

**Comment by DominicWatson** [comment]
Nice one, thanks @annbelievable . Merged into upcoming release.

**Pull request merged**
