### PR TITLE
PRESIDECMS-1110: MSSQL does not work with MAX function on a bit column type

### PR DESCRIPTION
**Pull request by philippPSH**
My first PR and hope it works. 
I tried the perform the unit tests but had technical problems with it (out of memory 2GB RAM)  and must investigate (spend more time).

I used an MSSQL 2016 database server and the problem came up while login with a new backend user.
Before it was used withe sysadmin only.

### CODE REVIEW

**Comment by DominicWatson** [comment]
This looks good @philippPSH - nice one. Can I double-check your reasoning here as it is a tough one to test? 

You may now end up with results like:

```
| granted | context_key |
=========================
| 0       | keya        |
-------------------------
| 0       | keya        |
-------------------------
| 1       | keya        |
-------------------------
| 0       | keyb        |
-------------------------
| 0       | keyb        |
-------------------------
```

Looping through and setting the struct as we do per context key means we still end up with the same result because you have ordered by `granted` _asc_.

Was that your thinking?

**Comment by philippPSH** [comment]
Hi,
the intention is to have a sorting by "context_key" and "granted"
The resulting query would list the granted=1 entry at the bottom.
(before, MAX (granted) was used to select granted=1 in case of both cases exists).

granted | context_key
-------- | ------------
 0          | keya      
 0          | keya       
 0          | keya        
 1          | keyb        


Do other projects have plenty entries in this table? We do not have an entry in the table  "psys_security_context_permission". We are using the backend only without any permission settings currently.

**Comment by DominicWatson** [comment]
Yes, some projects use this. For example, limit permissions to an object in datamanager. But what you say is exactly right 👍 will merge soon. Thanks for this.

**Comment by jjannek** [comment]
maybe to remove the duplicates it makes sense to add distinct = true?

**Comment by DominicWatson** [comment]
Great stuff, thanks @philippPSH. Merging into 10.8.66 (will also go into latest 10.9). @jjannek I'm hesistant with the distinct as that can cause more performance problems than it solves sometimes. I suggest we leave as is and revisit if anyone should have complaints (the numbers of records are very most likely to be very small and the calculation is cached).

**Pull request merged**
