### PR TITLE
PRESIDECMS-1903 control batch delete edit allowed operations

### PR DESCRIPTION
**Pull request by pixl8-brayden**
- add object attribute _batchEditable_ to have object level control, default to true
- add object attribute _batchDelete_ to have record delete but restricted batch delete, default to true

### CODE REVIEW

**Comment by DominicWatson** [comment]
I think it makes more sense to add this to the list of operations. i.e. `isOperationAllowed( "batchedit" )` / `isOperationAllowed( "batchdelete" )`. 

This would default to `true` unless `@datamanagerAllowedOperations` did not include it or `@datamanagerDisallowedOperations` contained either `edit` _or_ `batchedit` (and `delete` _or_ `batchdelete` for the batchdelete operation).

This has some backward compatibility issues but I'm happy enough with that. Nothing major I'd suggest.

So `batchedit` is **not** allowed when:

* `edit` is a disallowed operation
* `batchedit` is a disallowed operation
* `batchedit` is not included in an explicit allowed operations list

`batchdelete` is **not** allowed when:

* `delete` is a disallowed operation
* `delete` is a disallowed operation
* `batchdelete` is not included in an explicit allowed operations list

**Comment by pixl8-brayden** [comment]
Hi Dom,

I had updated the control to using data manger operations.

Thanks

**Comment by pixl8-brayden** [comment]
Hi @DominicWatson 

The controls had amend to use data manager operations and added admin permission for data manager.

Thanks

**Comment by DominicWatson** [comment]
Perfect, looks great - will merge into 10.12.0 and get some further QA on it.

**Pull request merged**
