### PR TITLE
fix bug when create a relationship from an object to itself in MsSqlA…

### PR DESCRIPTION
**Pull request by locrasia**
fix bug when create a relationship from an object to itself in MsSqlAdapter

### CODE REVIEW

**Comment by DominicWatson** [comment]
I see a lot of changes in the PR and as far as I am aware this is not a bug that is fixable in code. The answer here is to do `onupdate="no action" ondelete="no action"`.

Can you explain the changes in this PR?

**Comment by locrasia** [comment]
I just testing this version again and i wanna make sure if an object relate to itself then I set on update and on delete is no action.
But I got an issue in many-to-many relationship that I  did onupdate="no action" ondelete="no action" and nothing happened. As you can see via the attach file.
I just wonder how can I determine the type of the relationship (e.t many-to-many) in MsSqlAdapter.cfc ? Because I want to set no action for this type for sure

Best Regards,

Loc Nguyen, Team Leader

RASIA Ltd.

Anna Building, Quang Trung Software City,
Tan Chanh Hiep Ward, district 12,
Ho Chi Minh City - Vietnam

RASIA GmbH
Gollierplatz 10
80339 Munich - Germany
HRB 213399

Email  : loc@rasia.info
Skype : locnguyen210190
Phone: +84 98 554 6077
www.rasia.info

**Comment by DominicWatson** [comment]
Ok, if that had no effect, then that needs updating. The SQL server adapter cannot know the details of the relationship are.

My issue with this PR is that it seems to be making a lot of unrelated changes. Its as if you are starting from your old SQL Server adapter branch, rather than from the latest stable branch. Is this the case?

I'm closing this for now. I think this needs to be a new pull request or JIRA issue with details of the bug + potential fix that has been made as a fix branched from most recent stable. See https://docs.presidecms.com/contribguides/submittingchanges.html

**Comment by locrasia** [comment]
Yep, Maybe I on old branch. I will recheck this. I just push a new one. Can you close it too. Thank you !

Best Regards,

Loc Nguyen, Team Leader

logo_rasia
RASIA Ltd.

Anna Building, Quang Trung Software City,
Tan Chanh Hiep Ward, district 12,
Ho Chi Minh City - Vietnam

RASIA GmbH
Gollierplatz 10
80339 Munich - Germany
HRB 213399

Email  : loc@rasia.info
Skype : locnguyen210190
Phone: +84 98 554 6077
www.rasia.info

**Pull request closed without merging**
