### PR TITLE
PRESIDECMS-1122

### PR DESCRIPTION
**Pull request by john5onCheng**
Add timeout field

### CODE REVIEW

**Comment by john5onCheng** [comment]
hm.. how could I view the error log?

**Comment by DominicWatson** [comment]
Run the tests locally? https://docs.presidecms.com/contribguides/runningtests.html

**Comment by DominicWatson** [comment]
Looks great though btw. This will be useful 👍

**Comment by john5onCheng** [comment]
okay looks like test unit need update

**Comment by DominicWatson** [comment]
Yes, if you head over to https://travis-ci.org/pixl8/Preside-CMS you can see failed builds btw and see what messages there are there. Unfortunately, we don't have links to failed test results so you do need to run locally.

**Comment by john5onCheng** [comment]
green light this time :)

**Comment by john5onCheng** [comment]
Please help to merge to 10.7

**Comment by DominicWatson** [comment]
Great, thanks for this @john5onCheng. As this is a "nice to have" improvement, this will make its way into 10.9.0.

**Pull request merged**
