### PR TITLE
Initial commit for multilingual asset properties(PRESIDECMS-357)

### PR DESCRIPTION
**Pull request by cfmitrah**

### CODE REVIEW

**Comment by DominicWatson** [comment]
This looks fantastic Selva, thank you - it says "Initial commit...". Is it fully working?

**Comment by cfmitrah** [comment]
yeah It's working fully. But I am not sure about _checkPermission. Can you check it and let me know?
Thanks

**Comment by DominicWatson** [comment]
Yep, looks good :D (`_checkPermissions()` is just a private method implemented in that handler). I'll take a look at merging this asap. Nice work.

**Comment by DominicWatson** [comment]
Awesomeness, merged into upcoming 10.7.0 release

**Pull request merged**
